baseURL: https://nathaniel-keeler-photography.me
title: pioneer pics
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: ''

params:
  image: /images/banner.png
  logo: pioneer.png
  subtitle: Eternity is a minimalist Hugo theme designed for portfolio sites with a fresh feel.
  copyright: All rights reserved.
  author: Nathaniel Keeler
  dontShowSource: false
  dontShowLogo: false
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 2
  socials:
    - icon: 'fa-regular fa-envelope fa-lg'
      url: 'mailto:keeler@gmx.de'
      landing: true
    - icon: 'fa-brands fa-github fa-lg'
      url: 'https://github.com/nathanielkeeler'
      landing: true
    - icon: 'fa-brands fa-linkedin fa-lg'
      url: 'https://www.linkedin.com/in/nathaniel-keeler-596843233/'
      landing: true
  homepage: "/home" # todo: uncomment homepage, homepage link is mostly same with menu.main[0]
  specialPages:
    - home
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when set to true.
  plausible: ''
  disableWelcomePageBackground: false
  disableRadius: true
  moveIt: false # moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: home
      url: /home/
      weight: 1
    - name: analog
      url: /tags/analog/
      weight: 2
    - name: animals
      url: /tags/animals/
      weight: 3
    - name: astro
      url: /tags/astro/
      weight: 4
    - name: landscape
      url: /tags/landscape/
      weight: 5
    - name: people
      url: /tags/people/
      weight: 6
    - name: urban
      url: /tags/urban/
      weight: 7
    - name: archive
      url: /tags/archive/
      weight: 8
    - name: about
      url: /about/
      weight: 9
